name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Lambda function
        run: mvn package

      - name: Deploy to AWS Lambda
        uses: appleboy/aws-lambda-action@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          function_name: gameIdsUploader
          handler: DynamoDBUpdate::updateDynamoDB
          zip_file: target/gameRanking-1.0-SNAPSHOT.jar
